export const genreOptions = [
  "Self-help book",
  "Fiction",
  "Non-Fiction",
  "Science Fiction",
  "Mystery",
  "Romance",
  "Fantasy",
  "Historical Fiction",
  "Science",
  "Travel",
  "Psychology",
  "Art",
  "Biography",
  "Poetry",
  "Classic Literature",
  "Adventure",
  "Humor",
  "Contemporary",
  "Business",
  "Philosophy",
  "Politics",
  "Short Stories",
  "Educational",
  "Self-Development",
  "True Crime",
  "Western",
  "Mythology",
  "Steampunk",
  "Drama",
  "Science Fantasy",
  "Sports",
  "War",
  "Detective",
  "Cyberpunk",
  "Supernatural",
  "Other",
];
export const authorOptions = [
  "J.K. Rowling",
  "Stephen King",
  "Agatha Christie",
  "George R.R. Martin",
  "Jane Austen",
  "Dan Brown",
  "Neil Gaiman",
  "Tolkien",
  "Terry Pratchett",
  "Haruki Murakami",
  "Mark Twain",
  "H.P. Lovecraft",
  "Charles Dickens",
  "Gabriel Garcia Marquez",
  "Khaled Hosseini",
  "Leo Tolstoy",
  "Arthur Conan Doyle",
  "J.R.R. Tolkien",
  "Victor Hugo",
  "Oscar Wilde",
  "Fyodor Dostoevsky",
  "Virginia Woolf",
  "Ray Bradbury",
  "Hermann Hesse",
  "Ernest Hemingway",
  "Albert Camus",
  "Agatha Christie",
  "Jules Verne",
  "J.D. Salinger",
  "Jane Austen",
  "Mary Shelley",
  "George Orwell",
  "Emily Dickinson",
  "Leo Tolstoy",
  "Charles Dickens",
  "Toni Morrison",
  "Edgar Allan Poe",
  "Oscar Wilde",
  "F. Scott Fitzgerald",
  "Walt Whitman",
];

export const questions = [
  "What's your preferred genre?",
  "Who are your favorite authors?",
  "Do you prefer paperbacks or ebooks?",
  "Do you prefer old books or new ones?",
];

export const bookTypeOptions = ["Paper Books", "eBooks"];

export const bookAgeOptions = ["Old Books", "New Ones"];

export const images = [
  "https://ucarecdn.com/472f5659-20c0-4135-be84-8b7534ed5c0c/ego1.png",
  "https://ucarecdn.com/9fbe3178-775b-41de-a84e-fd5bcdddc3ff/51xp6sg2TCL_AC_UF10001000_QL80_.jpg",
  "https://ucarecdn.com/e0336138-b932-4328-8910-f065e4605075/614fg2kN44L_AC_UF10001000_QL80_.jpg",
];
